accessing
mapPCH

	^ Dictionary new
		at: 0 put: 'square';
		at: 1 put: 'circle';
		at: 2 put: 'triangle point up';
		at: 3 put: 'plus';
		at: 4 put: 'cross';
		at: 5 put: 'diamond';
		at: 6 put: 'triangle point down';
		at: 7 put: 'square cross';
		at: 8 put: 'star';
		at: 9 put: 'diamond plus';
		at: 10 put: 'circle plus';
		at: 11 put: 'triangles up and down';
		at: 12 put: 'square plus';
		at: 13 put: 'circle cross';
		at: 14 put: 'square and triangle down';
		at: 15 put: 'filled square blue';
		at: 16 put: 'filled circle blue';
		at: 17 put: 'filled triangle point up blue';
		at: 18 put: 'filled diamond blue';
		at: 19 put: 'solid circle blue';
		at: 20 put: 'bullet (smaller circle)';
		at: 21 put: 'filled circle red';
		at: 22 put: 'filled square red';
		at: 23 put: 'filled diamond red';
		at: 24 put: 'filled triangle point up red';
		at: 25 put: 'filled triangle point down red';
		yourself
		