syntax
langMicrodown
	" From https://github.com/pillar-markup/MicroDown "

	^ '#Header

```language=Pharo&caption=Beautiful&label=Fig1
code
```
   
> Boring quote block 
> Don''t use me!

![Pharo is cool](http://pharo.org)
	
- list
1. ordered list 

`in text` and for Pharo hyperlinks to class, method and package: 
`Point`, `Point class`, `Point>>#setX:setY:`, `#’Microdown-Tests’ (for packages)

References: *@ref*'