defaults
defaultContributeText

	^ '**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

If you have discovered a bug or have a feature suggestion, feel free to create an issue on Github.
If you have any suggestions for how this package could be improved, please get in touch or suggest an improvement using the GitHub issues page.
If you''d like to make some changes yourself, see the following:    

  - Fork this repository to your own GitHub account using the web interface.
  - Clone it to your local device: `git clone git@github.com:YOUR_NAME/.git`
  - Do some modifications
    - If you add some feature, create your feature branch: `git checkout -b MY_NEW_FEATURE`
  - Test.
  - Add <your GitHub username> to add yourself as author below.
  - Finally, submit a pull request with your changes!
  - This project follows the [all-contributors specification](https://github.com/kentcdodds/all-contributors). Contributions of any kind are welcome!
'
