SystemOrganization addCategory: #'CodeGenerator-Readme'!
SystemOrganization addCategory: #'CodeGenerator-Readme-Badges'!
SystemOrganization addCategory: #'CodeGenerator-Readme-Badges-ShieldsIO'!
SystemOrganization addCategory: #'CodeGenerator-Readme-Core'!
SystemOrganization addCategory: #'CodeGenerator-Readme-Licenses-SPDX'!
SystemOrganization addCategory: #'CodeGenerator-Readme-Templates'!
SystemOrganization addCategory: #'CodeGenerator-Readme-UI'!
