accessing
languagesList
	" Answer a <Collection> of available language for tagging scripts "
	
	^ { 
		'Markdown' .
		'Microdown' .
		'Pillar' .
		'Multimarkdown' .
		'Pandoc' .
		'Kramdown' .
		'Markdown Extra' .
		'Markua' .
		'Maruku' .
		'Markdown2' .
		'Remarkable' .
		'Showdown' .
		'Ghost' .
		'GitLab' .
		'Haroopad' .
		'iA Writer' .
		'Redcarpet' .
		'ScholarlyMarkdown' .
		'Taiga' .
		'Trello'
		}