private - sections
sections
	" Titles for sections with a list "

	^ #(
	'Table of Contents'
	'Synopsis'
	'Introduction'
	'Motivation'
	'Description'
	'Screenshots'
	'Requirements'
	'Installation'
	'Built With'
	'Configuration'
	'Usage'
	'Usage Notes'
	'Examples'
	'Tests'
	'Deployment'
	'Translations'
	'Contribute'
	'Troubleshooting'
	'Contact'
	'Authors'
	'Contributors'
	'Maintainers'
	'License'
	)