templates-contribute
contributeList02

	^ 'Working on your first Pull Request? You can learn how from this free series How to Contribute to an Open Source Project on GitHub

If you have discovered a bug or have a feature suggestion, feel free to create an issue on Github. If you have any suggestions for how this package could be improved, please get in touch or suggest an improvement using the GitHub issues page. If you''d like to make some changes yourself, see the following:

  - Fork this repository to your own GitHub account and then clone it to your local device
  - Do some modifications
  - Test.
  - Add to add yourself as author below.
  - Finally, submit a pull request with your changes!
  - This project follows the all-contributors specification. Contributions of any kind are welcome!
'